### ISSUE TITLE
don't use sha1 as default

### ISSUE THREAD

**Issue by dominictarr** [nasser/oddball#1]
sha256 is okay, even if you truncate it to 20 bytes, here is a great post that illustrates the problem:

https://www.schneier.com/blog/archives/2012/10/when_will_we_se.html

**Comment by nasser** [comment]
Good point. Updated in 150c8fe.

One related question before I close this: in the case of a collision, git keeps the old data. The current implementation of oddball would overwrite it. Which, if any, makes more sense for a data store?

**Comment by dominictarr** [comment]
For this kind of thing, a collision should be an _astronomically unlikely event_.

The point of a cryptographically secure hash is that collisions are so unlikely that you'd be more worried about other things, such as the sun expanding and swallowing the earth - as described in [this fox news article](http://www.foxnews.com/story/2009/08/03/could-earth-be-swallowed-by-dying-sun/)

That said, we humans are pretty new to this cryptographic hash thing (1978) so we could have made some mistakes (as we did with sha1, md5 etc) maybe weaknesses will be discovered in your algorithm,
and in that case, it's more like the system slowly weakens, until an attack becomes feasible.

All that said, maybe keeping the old value would create more predictable behavior, but it would depend on the application.

**Comment by nasser** [comment]
Noted. I'll keep it overwriting for now to avoid doing a check for an astronomically unlikely event.

Thanks for the feedback!
